name: documentation
on:
  pull_request:
    branches:
    - master
    - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9.1
      - run: pip install -r requirements-dev.txt
      - run: mkdocs gh-deploy --force
